{% set name = "auton-survival" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/auton_survival-{{ version }}.tar.gz
  sha256: 7843ec38cebe87faf6339631b936c28723a069049d2b01519f358881df1a0db6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base
    - numpy
    - pandas
    - python
    - scikit-learn
    - scikit-survival
    - torch
    - torchvision
    - tqdm

test:
  imports:
    - auton_survival
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://autonlab.github.io/auton-survival/
  summary: Provides a flexible API for various problems in survival analysis, including regression, counterfactual estimation, and phenotyping.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - injuredroman
