{% set name = "auton-survival" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/auton_survival-{{ version }}.tar.gz
  sha256: 71893a0250ca21918f88b92af3c938b4200e84af138deedb98b4deb180845c08

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.7
    - scikit-learn
    - scikit-survival
    - pytorch
    - torchvision
    - tqdm

test:
  imports:
    - auton_survival
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://autonlab.github.io/auton-survival/
  summary: Provides a flexible API for various problems in survival analysis, including regression, counterfactual estimation, and phenotyping.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - injuredroman
